[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则-在线更新版

;去广告：支持
;自动测速：不支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：不支持
;增强国外GFW：支持

ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=Google,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=Google,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=MicroSoft,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=Apple,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=Telegram,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=Media,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=Proxies,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
;ruleset=DIRECT,[]GEOIP,LAN
ruleset=DIRECT,[]GEOIP,CN
ruleset=Final,[]FINAL

custom_proxy_group=Proxies`select`.*
custom_proxy_group=Telegram`select`[]Proxies`[]DIRECT`[]HK`[]JP`[]SG`[]TW`[]US
custom_proxy_group=Media`select`[]Proxies`[]DIRECT`[]HK`[]JP`[]SG`[]TW`[]US
custom_proxy_group=MicroSoft`select`[]DIRECT`[]Proxies`[]HK`[]JP`[]SG`[]TW`[]US
custom_proxy_group=Apple`select`[]DIRECT`[]Proxies`[]HK`[]JP`[]SG`[]TW`[]US
custom_proxy_group=Google`select`[]Proxies`[]DIRECT`[]HK`[]JP`[]SG`[]TW`[]US
custom_proxy_group=Final`select`[]Proxies`[]DIRECT
custom_proxy_group=HK`select`港|HK|Hong Kong`http://www.gstatic.com/generate_204`600
custom_proxy_group=SG`select`新|新加坡|狮城|SG|Singapore`http://www.gstatic.com/generate_204`600
custom_proxy_group=TW`select`台|台湾|台灣|新北|彰化|深台|CHT|HINET|TW|Taiwan`http://www.gstatic.com/generate_204`600
custom_proxy_group=JP`select`日((?!用).)+|[^-]日|东京|大阪|埼玉|JP|Japan`http://www.gstatic.com/generate_204`600
custom_proxy_group=US`select`美|洛杉矶|圣何塞|西雅图|US|USA|United States`http://www.gstatic.com/generate_204`600
