name: update_gd

on:
  schedule:
    #- cron: '15 9,23 * * *'
    - cron: '45 21 * * *'
  push:
    branches:
      - main
    paths: 
      - '**.js'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y yt-dlp sed nmap
        
    - name: Run Multitest Script
      #working-directory: zubo/speedtest
      run: |
       bash $GITHUB_WORKSPACE/gd.sh
        
    - name: Update Results
      run: |
        cd $GITHUB_WORKSPACE
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update files"
        git push
